---

- include: install-debian-custom.yml
  when: telegraf_install_version and telegraf_install_version != 'packaged'

- include: install-debian-packaged.yml
  when: not telegraf_install_version or telegraf_install_version == 'packaged'
