---

#- name: Install any necessary dependencies [RHEL/CentOS]
#  become: true
#  become_user: "{{ telegraf_install_user }}"
#  yum:
#    name: libselinux-python
#    state: installed

- name: Add InfluxData repository [RHEL/CentOS]
  become: true
  become_user: "{{ telegraf_install_user }}"
  yum_repository:
    enabled: yes
    state: present
    description: telegraf Repository - RHEL $releasever
    name: telegraf
    baseurl: https://repos.influxdata.com/rhel/$releasever/$basearch/stable
    gpgcheck: yes
    gpgkey: https://repos.influxdata.com/influxdb.key

- name: Install telegraf package [RHEL/CentOS]
  become: true
  become_user: "{{ telegraf_install_user }}"
  yum:
    name: telegraf
    state: installed
  notify:
    - restart telegraf
