---

- name: Setup
  include: setup.yml

- name: start service
  become: true
  become_user: "{{ telegraf_install_user }}"
  service:
    enabled: yes
    name: telegraf
    state: started
  tags:
    - telegraf
