---

- include: install.yml
  tags:
    - telegraf
    - packages

- include: configure.yml
  tags:
    - telegraf
    - configuration

- name: start service
  become: true
  become_user: "{{ telegraf_install_user }}"
  service:
    enabled: yes
    name: telegraf
    state: started
  tags:
    - telegraf
    - service
