---

- name: Install libselinux-python.
  become: true
  become_user: "{{ telegraf_install_user }}"
  yum:
    name: libselinux-python
    state: installed
  tags:
    - telegraf
    - packages

- name: Add telegraf repository.
  become: true
  become_user: "{{ telegraf_install_user }}"
  yum_repository:
    state: present
    description: telegraf Repository - RHEL $releasever
    name: telegraf
    baseurl: https://repos.influxdata.com/rhel/$releasever/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://repos.influxdata.com/influxdb.key
  tags:
    - telegraf
    - packages

- name: Install telegraf.
  become: true
  become_user: "{{ telegraf_install_user }}"
  yum:
    name: telegraf
    state: installed
  notify:
    - restart telegraf
  tags:
    - telegraf
    - packages
