---

- name: Setup custom version for RedHat base distribution (RedHat, CentOS)
  include: setup-RedHat-custom.yml
  when: telegraf_install_version and telegraf_install_version != 'packaged'

- name: Setup packaged version for RedHat base distribution (RedHat, CentOS)
  include: setup-RedHat-packaged.yml
  when: not telegraf_install_version or telegraf_install_version == 'packaged'
